### PR TITLE
Composer cleanup

### PR DESCRIPTION
**Pull request by Soullivaneuh**
dev minimum stability with prefer-stable option.

knp/paginator-bundle `^2.4.2` to prevent following error:

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "knp_paginator.helper.processor" has a dependency on a non-existent service "templating.helper.router".
```

### CODE REVIEW

**Comment by rande** [comment]
I will revert this commit as some sonata's bundles do not get the latest commit.

**Comment by Soullivaneuh** [comment]
@rande which one? Could fix the composer.json instead.

**Comment by rande** [comment]
@Soullivaneuh you should see in the build https://codeship.com/projects/84753/builds/6211305

**Comment by Soullivaneuh** [comment]
Are you talking about deprecated fix?

Well for example if a fixed package has `2.2.2` at last stable version, just add `^2.2.3` on requirement.

This will get the dev-master version until new stable release is pushed.

**Comment by Soullivaneuh** [comment]
Will take a look right now.

**Comment by rande** [comment]
The old configuration make sure  to get all dev versions ;)

**Comment by rande** [comment]
and stable version for others bundles

**Comment by Soullivaneuh** [comment]
Depends of what you want.

Personally I prefer mark minimum requirements to get this sandbox working instead of getting all dev "to be sure" and have to remove it when you stabilize it.

> and stable version for others bundles

I also did that because all sonata package aren't on dev version.

I could work on it to correct composer.json to get test working with latest version or just revert it.

Your choice. :+1:

**Comment by Soullivaneuh** [comment]
> I also did that because all sonata package aren't on dev version.

Well, only `sonata-project/seo-bundle` apparently. :-P

As your choice, just tell me to know if I have to work on it or not.

**Comment by rande** [comment]
I think reverting back, will help to release one by one sonata's bundles

**Comment by Soullivaneuh** [comment]
Well, I wont touch composer.json on sonata-sandbox then, let you play with it. ;-)

Another thing more or less related: Could be great to define the new versionning rules with branching management like Symfony does and complete contributing docs before release new minor version of this bundle, isn't it? Where is the better place to talk about it? I was thinking about start a PR/issue on sonata-admin to start discussing.

**Pull request merged**
