### PR TITLE
Drop SonataCoreBundle

### PR DESCRIPTION
**Pull request by wbloszyk**
Drop SonataCoreBundle from sanbox (Sonata 3)

### CODE REVIEW

**Comment by wbloszyk** [comment]
@jordisala1991 After this PR we can try to run github actions or travis like you wrote in https://github.com/sonata-project/sandbox/pull/624#issuecomment-642132960.

BTW Can you ping contributors?
This is last PR from https://github.com/sonata-project/dev-kit/issues/697

**Comment by jordisala1991** [comment]
Is the PR ready? all test passes?

**Comment by wbloszyk** [comment]
PR ready. Tests should be fix.

**Comment by jordisala1991** [comment]
Thank you @wbloszyk , now we need github actions or travis. I will try to setup this week

**Pull request merged**
