### PR TITLE
Modernising sandbox step 1 attempt 2

### PR DESCRIPTION
**Pull request by Xymanek**
Redone modernization effort based on `2.4-develop` branch (see #606)

### CODE REVIEW

**Comment by Xymanek** [comment]
Ok basic functionality is working - homepage (as well as bunch of other ones) work, admin also kinda works. Maybe it's time to merge?

**Comment by kunicmarko20** [comment]
What is kinda? Should you maybe try and address all issues here? cc @sonata-project/contributors

**Comment by Xymanek** [comment]
> What is kinda

Console and homepage work - that was my initial goal. Admin also works. However assets are broken/missing all over the place, doctrine is complaining about some missing properties, etc. Also a lot of functionality isn't even tested

> try and address all issues here

I would prefer to make separate PRs instead of one huge one

**Comment by OskarStark** [comment]
Thank you @Xymanek 👍

**Comment by Xymanek** [comment]
Well, it's just a start...

**Pull request merged**
