### PR TITLE
Add static code analysis through GitHub actions

### PR DESCRIPTION
**Pull request by phansys**
IMO, we are able to configure this project at "dev-kit".

### CODE REVIEW

**Comment by phansys** [comment]
IMO, the fixes are RTM. We must decide what to do with the workflow configuration.

**Comment by phansys** [comment]
These are the analysis results In my fork: https://github.com/phansys/sandbox/actions.

**Comment by jordisala1991** [comment]
Can you check phpstan failures?

**Comment by phansys** [comment]
>Can you check phpstan failures?

Sure! They are now fixed :+1:

**Comment by jordisala1991** [comment]
Thank you @phansys

**Pull request merged**
