### PR TITLE
Remove unused use statement

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please rebase?

Thank you @sagikazarmark

**Comment by sagikazarmark** [comment]
Done

**Comment by OskarStark** [comment]
My IDE also marks the FormTypeInterface unused, can you please check that and if yes update your PR?

bildschirmfoto 2015-09-29 um 15 34 38

**Comment by sagikazarmark** [comment]
Yeah, my IDE didn't mark it because of some sort of other error.

**Comment by OskarStark** [comment]
Thank you @sagikazarmark :smile:

**Pull request merged**
