### PR TITLE
don't overwrite var -> use $mediaManager instead

### PR DESCRIPTION
**Pull request by OskarStark**
use ```$mediaManager```, instead of ```$manager```, which is ambiguous.

no code change, this is just for readability and fixes the code completion of the IDE

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Why this? Is it a fix? A Fix of what?

**Comment by TomasVotruba** [comment]
I guess it's just more clear naming, as there is `->galleryManager` and `->mediaManager` and property named `$manager`, which is ambiguous.

**Comment by OskarStark** [comment]
yes @TomasVotruba

**Comment by TomasVotruba** [comment]
@OskarStark It might be helpful to write this in description of PR, since it's easier to read source then.

**Comment by OskarStark** [comment]
done @TomasVotruba

**Comment by TomasVotruba** [comment]
@OskarStark Thank you.

**Comment by Soullivaneuh** [comment]
On the original code, `$manager` parameter is overridden by `getMediaManager`.

With your code, not anymore. I don't know if this parameter is now useful.

ping @rande.

**Comment by TomasVotruba** [comment]
@Soullivaneuh It's probably enforced by interface. Not relevant though.

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
